In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
import numpy as np
import pandas as pd
full_review_df = pd.read_csv("/content/drive/Shareddrives/NLP모델링/강의계획서/reviews_label.csv")
full_review_df.shape

(27142, 15)

In [ ]:
full_review_df.head()

,Unnamed: 0,학정번호,강의명,교수명,유의사항,별점,수강시기,강의평,강의명/교수명,성적,로드,강의력,교수님성향,강의자료질,족보여부
0,15,YCC1002-01-00,대학기본영어Ⅱ,오진숙,"대면강의, 절대평가",5.0,17년 2학기,어렵지 않은 내용으로 탄탄한 기본기를 다져주는 유익한 수업,대학기본영어Ⅱ/오진숙,-1.0,-1.0,0.5,-1.0,-1.0,-1.0
1,16,YCC1002-01-00,대학기본영어Ⅱ,오진숙,"대면강의, 절대평가",5.0,19년 2학기,교수님 너무 귀여우심... 사랑해요\n자잘한 과제들 귀찮긴 했지만 시간투자 그렇게 ...,대학기본영어Ⅱ/오진숙,-1.0,0.5,0.5,1.0,-1.0,-1.0
2,17,YCC1002-01-00,대학기본영어Ⅱ,오진숙,"대면강의, 절대평가",5.0,19년 2학기,완전 좋음 2학기 때 내가 살아있던 이유.. 기말 때 갑자기 시험을 세번 본 거는 ...,대학기본영어Ⅱ/오진숙,1.0,0.5,0.5,1.0,-1.0,-1.0
3,18,YCC1002-01-00,대학기본영어Ⅱ,오진숙,"대면강의, 절대평가",4.0,19년 2학기,영어 말하는 데에 자신감을 얻고 싶으면 추천 다만 과제는 자잘한게 많고 필자는 1학...,대학기본영어Ⅱ/오진숙,1.0,0.5,0.5,1.0,-1.0,-1.0
4,19,YCC1002-01-00,대학기본영어Ⅱ,오진숙,"대면강의, 절대평가",5.0,16년 2학기,수강당시에는 조모임 비율도 높았고 발음 중시하시는건 왜 그러시는지 잘 이해가지 않지...,대학기본영어Ⅱ/오진숙,1.0,0.5,0.5,1.0,-1.0,-1.0

In [ ]:
review_df = full_review_df[["학정번호", "강의명/교수명", "별점", "성적", "로드", "강의력", "교수님성향", "강의자료질", "족보여부"]]    # 필요한 컬럼만 선택
review_df.rename(columns={"별점":"[별점]", 
                          "성적":"[성적]", 
                          "로드":"[로드]", 
                          "강의력":"[강의력]", 
                          "교수님성향":"[교수님성향]", 
                          "강의자료질":"[강의자료질]", 
                          "족보여부":"[족보여부]"}, inplace=True)
review_df = review_df.replace(-1, np.NaN)   # -1을 결측치로 변경
review_df = review_df.groupby(["강의명/교수명"], as_index=True).mean()   # 각 강의별 컬럼값을 평균내서 한 행으로 요약 + 강의명/교수명을 인덱스로
review_df

/usr/local/lib/python3.7/dist-packages/pandas/core/frame.py:5047: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  errors=errors,

,[별점],[성적],[로드],[강의력],[교수님성향],[강의자료질],[족보여부]
강의명/교수명,,,,,,,
2D디지털디자인/김현정,4.636364,0.5,0.0,0.5,1.0,0.5,NaN
CELL BIOLOGY (1)/구남온,2.461538,0.5,1.0,0.0,1.0,0.5,NaN
EASTERN CIVILIZATION/호프마이클,3.420000,0.5,0.0,0.5,1.0,0.5,1.0
ENGLISH FOR PHYSICAL SCIENCES AND ENGINEERING/유제왕,4.652174,1.0,0.5,1.0,1.0,0.5,NaN
ENGLISH FOR PHYSICAL SCIENCES AND ENGINEERING/휴벨브라이언,4.818182,1.0,0.5,0.5,1.0,0.5,NaN
...,...,...,...,...,...,...,...
회계원리(1)/기랄안드레스,3.338028,0.5,0.5,0.0,0.5,0.5,1.0
회계원리(1)/이한솔,4.840000,1.0,0.5,1.0,1.0,0.5,0.5
회계원리(1)/이호영,2.816327,0.5,0.5,0.0,0.5,0.5,0.5
회계원리(1)/최원욱,4.608696,0.5,0.5,1.0,1.0,0.5,0.5
후생경제학/김세민,3.290698,1.0,1.0,0.0,1.0,0.5,1.0

In [ ]:
def max_sum_sim(doc_embedding, candidate_embeddings, words, top_n, nr_candidates):
    # 문서와 각 키워드들 간의 유사도
    distances = cosine_similarity(doc_embedding, candidate_embeddings)

    # 각 키워드들 간의 유사도
    distances_candidates = cosine_similarity(candidate_embeddings, candidate_embeddings)

    # 코사인 유사도에 기반하여 키워드들 중 상위 top_n개의 단어를 pick
    words_idx = list(distances.argsort()[0][-nr_candidates:])   
    # argsort(): 작은 값부터 순서대로 데이터의 위치를 반환
    # words_idx에는 문서와의 유사도가 높은 nr_candidates개 단어의 위치가 들어가 있음
    words_vals = [candidates[index] for index in words_idx]     
    # words_vals에는 words_idx의 위치에 해당하는 단어들이 들어가 있음
    distances_candidates = distances_candidates[np.ix_(words_idx, words_idx)]   
    # np.ix_: 서로 다른 shape을 가진 배열들을 묶어서 처리

    # 각 키워드들 중에서 가장 덜 유사한 키워드들간의 조합을 계산
    min_sim = np.inf
    candidate = None
    for combination in itertools.combinations(range(len(words_idx)), top_n):
        sim = sum([distances_candidates[i][j] 
                   for i in combination for j in combination if i != j])
        if sim < min_sim:
            candidate = combination
            min_sim = sim

    return [words_vals[idx] for idx in candidate]